services:
  db:
    image: postgres:16.3-bookworm
    environment:
      POSTGRES_DB: audiomania
      POSTGRES_PASSWORD: audiomania
    ports:
      - 5432:5432
  storage:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    environment:
      MINIO_ROOT_USER: audiomania
      MINIO_ROOT_PASSWORD: audiomania
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - ./data:/data

